[package]
name = "ibillingsley/one-slime-army"
version = "1.1.1"
description = "One Slime Army is an arcade endless wave survival game for the WASM-4 fantasy console"
license = "ISC"
readme = "README.md"
repository = "https://github.com/ibillingsley/wasm4-gamejam"

[[module]]
name = "one-slime-army"
source = "dist/one-slime-army.wasm"
abi = "wasm4"
interfaces = { wasm4 = "0.0.1" }

[[command]]
runner = "wasm4@0.0.1"
name = "play"
module = "one-slime-army"
